### ISSUE TITLE
Custom meta value do not work with Nuxt 1.1.1

### ISSUE THREAD

**Issue by hauleth** [nuxt-community/router-module#10]
With 1.1.1 `meta` field of `vm.$route` is set to `[ {} ]` for some reason.

**Comment by Atinux** [comment]
It will be fixed with Nuxt 2.0

**Comment by hauleth** [comment]
@Atinux when will that happen? Because it is a little painful that such breaking change was introduced between 1.0.0-beta and 1.0.0.

**Comment by Atinux** [comment]
Actually, it's not a breaking change since it did not exists in 1.0.0-beta.

**Comment by hauleth** [comment]
@Atinux my bad, I have been using 1.0.0-rc.11 and `meta` field was working perfectly fine.
