### ISSUE TITLE
SPA in subdirectory/router base.

### ISSUE THREAD

**Issue by cbodin** [nuxt-community/router-module#12]
Generating an SPA with a router base set will automatically add a `<base href="">` so the application can be loaded in a subdirectoy.

Can this be accomplished when using the router-module or will i need to set the base-href and rewrite all script tags myself?

**Comment by Atinux** [comment]
You can set router.base option in nuxt.config.js and add the base option in your router as well :)

**Comment by cbodin** [comment]
Yeah, but that doesn't include the `<base href="">` tag or append the base to the `src=""` attribute of the script tag.

**Comment by Atinux** [comment]
Weird, did you add the base attribute to your Vue router as well?

**Comment by cbodin** [comment]
Just tried reproducing it using the latest version of everything and cannot reproduce, closing :)
