### ISSUE TITLE
typescript does not work

### ISSUE THREAD

**Issue by jasonc08** [nuxt-community/router-module#13]
ERROR  Nuxt error

  Error: [nuxt-router-module] Please create a router.js file in your source folder.

**Comment by Atinux** [comment]
Like it says, you have to manually create a router.js in your project directory.

**Comment by riddla** [comment]
I think he was referring to using a `router.ts` instead of `router.js`. I tested this locally by changing the [`routerPath`](https://github.com/nuxt-community/router-module/blob/master/src/index.js#L10) in the library itself and it worked without problems (in `nuxt-ts` context).

**Comment by riddla** [comment]
Should I open a pull request with detecting either a `router.ts` or `router.js`?

Something like ...

```javascript
  // [...]
  
  let routerPath = resolve(this.options.srcDir, 'router.js');
  if (!existsSync(routerPath)) {
    routerPath = resolve(this.options.srcDir, 'router.ts');
  }

  // Check if router.js is defined
  if (!existsSync(routerPath))
    throw new Error(
      '[nuxt-router-module] Please create a router.js (or router.ts) file in your source folder.'
    );
   
    // [...]
```

**Comment by wizardpisces** [comment]
Any progress? Still not working with router.ts

**Comment by lifenautjoe** [comment]
Hey there @Altinux, 

This module is still not usable with typescript...

**Comment by Atinux** [comment]
Maybe @kevinmarrec can help on this one :)

**Comment by zecka** [comment]
Any alternative now to have a custom rooter with typescript ?

**Comment by Onefivefournine** [comment]
Issue is still relevant, @Atinux, @kevinmarrec 
I think @riddla proposed a quite simple solution [here](https://github.com/nuxt-community/router-module/issues/13#issuecomment-458882353)
