### ISSUE TITLE
Lazy loading

### ISSUE THREAD

**Issue by wellnine** [nuxt-community/router-module#14]
Hi there. Thank you for your module.
I am trying to use it in my project instead _pages_ mechanism. Everything are going fine except lazy-loading (eg. code splitting)

I tried to use this configuration, like in Vue-router docs but it doesn't work somehow

```import Vue from "vue"
import Router from "vue-router"

import Main from "~/components/Main"

const Customer = () => import("~/components/customer/index.vue");


// import Customer from "~/components/customer";
import Overview from "~/components/customer/overview";
import Profile from "~/components/customer/profile";
import Cards from "~/components/customer/cards";

Vue.use(Router);

export function createRouter() {
	return new Router({
		mode: "history",
		routes: [
			{
				path: "/",
				component: Main
			},
			{
				path: "/customer",
				component: Customer,
				children: [
					{
						path : "",
						component : Overview
					},
					{
						path : "profile",
						component : Profile
					},
					{
						path : "cards",
						component : Cards
					}
				]
			}
		]
	})
}
```

When I tried to load the Customer module I got this issue
`Failed to mount component: template or render function not defined.`

My component is deadly simple

```
<template>
    <router-view></router-view>
</template>

<script lang="ts">

	import Vue from "vue";
	import Component from "nuxt-class-component";

	@Component
	export default class extends Vue {}
</script>
```

could you, please, help me with this issue? May be I'm doing something wrong.

**Comment by sschadwick** [comment]
Did you get it working? This worked for me:

```js
component: () => import('./Component').then(() => m.default || m)
```

**Comment by StriveNuby** [comment]
@sschadwick Thank you very much for your method, you may have missed the variable 

> component: () => import('~/views/dashboard/index').then(m => m.default || m)

otherwise

![image](https://user-images.githubusercontent.com/18200762/46254016-60659a80-c4bb-11e8-93d9-65d90c3ddd25.png)

**Comment by sschadwick** [comment]
@StriveNuby Indeed I did, good catch!

**Comment by jessielaf** [comment]
Maybe I am a bit late but is it intended to have `.then(m => m.default || m)`?

**Comment by Upd4ting** [comment]
Hey here, is that normal that if I'm using lazy loading in the router, i'm getting SSR rendering issues: [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.

but if I import staticly I don't have any problem

**Comment by Radiergummi** [comment]
While the solution by @sschadwick works, this cannot be the final answer to this problem?

**Comment by mathieutu** [comment]
Yeah, I can't understand why we need to manually take the default export here, while standard async imports work well in components, and in a standard vue-cli/vue-router project.

All the vue-router examples about lazy imports omit the `.then(m => m.default)`, and they work well.

Could it be a nuxt related issue?

Thanks.

**Comment by mathieutu** [comment]
see #82 for a more recent discussion.
