### ISSUE TITLE
router.js is ignored from eslint-loader linting

### ISSUE THREAD

**Issue by sobolevn** [nuxt-community/router-module#17]
## What I expect to happen

I expect that my `pre` loader configuration will lint this file.

That's how I configure it:

```js
        // Enabling eslint in nuxt.config.js:
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
```

## What actually happens

`router.js` is just ignored from linting.
You can write any styles you want, nothing will happen.

It only happens with the file. Other files are linted as usual.

## Steps to reproduce

1. Install https://github.com/wemake-services/wemake-vue-template
2. Mess up something inside `router.js` for example: `mode:'history',`  (no spaces)
3. Run `yarn dev`

There will be no error. But there should be one.

## Comments

I guess it happens because `webpack` does not actually `require()` this file during the client build.
Related: https://github.com/wemake-services/wemake-vue-template/issues/587

## PS

I have tried to submit a bug via `cmty` twice! At the first try it just removed everything I had and showed me this message (I was unable to select any version):
<img width="323" alt="2018-06-09 22 21 19" src="https://user-images.githubusercontent.com/4660275/41195337-e05e3976-6c33-11e8-8423-d2d56f99b8b7.png">

Then it just went offline (but I have already copied my issue text this time!):
<img width="927" alt="2018-06-09 22 22 31" src="https://user-images.githubusercontent.com/4660275/41195343-f72aeb9a-6c33-11e8-8bc6-00708ccd6430.png">

**Comment by Atinux** [comment]
Hi @sobolevn 

I updated it as bug report now :)
