### ISSUE TITLE
`keepDefaultRouter ` Not working with Nuxt 2.x after they refactored everything

### ISSUE THREAD

**Issue by gapipro** [nuxt-community/router-module#26]
### Version

[v1.1.0](https://github.com/router-module/releases/tag/v1.1.0)

### Reproduction link

[https://jsfiddle.net/](https://jsfiddle.net/)

### Steps to reproduce

1. Have a nuxt 2.x project
2. install router-module and enable `keepDefaultRouter` option
3. try to run app
4. error: ` Cannot find module 'nuxt/lib/app/router'`

### What is expected ?

App should start up normally. 

### What is actually happening?

Error:  `Cannot find module 'nuxt/lib/app/router'`

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/router-module/issues/c30">#c30</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
@gapipro this is fixed for next version that will be released soon

**Comment by ricardogobbosouza** [comment]
@gapipro fixed on version `^1.2.0`, please upgrade!
