### ISSUE TITLE
Don't require /router.js in production .. it's not even used

### ISSUE THREAD

**Issue by hecktarzuli** [nuxt-community/router-module#28]
### What problem does this feature solve?

Currently after you do a build and deploy to a server, you have to include /router.js even though it ISN'T EVEN USED!
It would be nice to wrap most of this module in a build hook since that's all it's really dealing with anyway.

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/router-module/issues/c31">#c31</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
@hecktarzuli 
I do not know if I understand the problem, could you give an example ?

**Comment by hecktarzuli** [comment]
The problem seems to be with this line: https://github.com/nuxt-community/router-module/blob/469d4ad912fc84067f87b644cde06f1e40fc023f/lib/module.js#L22

You are checking if root/router.js file exists no matter what.  This means, at run time (even when not building) the file HAS to exist even when it's not even needed in production since your module copies that into .nuxt/router.js already.

I would think it would only do that check if it's actually building.

**Comment by ricardogobbosouza** [comment]
The router.js is no longer copied but imported by the plugin, not yet the problem

**Comment by ricardogobbosouza** [comment]
@hecktarzuli 
What we can do is run inside the hook `build:before`, what do you think?

**Comment by hecktarzuli** [comment]
We are using version 1.1.  I didn't know this had been updated recently.  If this doesn't copy the file, an just uses the original at runtime, that's fine.

**Comment by ricardogobbosouza** [comment]
This is exactly what is being done in version v1.3.0
