### ISSUE TITLE
nuxt generate - no such file or directory

### ISSUE THREAD

**Issue by robyedlin** [nuxt-community/router-module#3]
With fresh Nuxt and router-module 1.0.1, `nuxt generate` produces the following error:

```
Generating routes
{ Error: ENOENT: no such file or directory, lstat '/home/ubuntu/workspace/dist/index.html'
    at Error (native)
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/ubuntu/workspace/dist/index.html' }
```

**Comment by Atinux** [comment]
Hi @robyedlin 

You have to list all your routes for `nuxt generate` since Nuxt.js `pages/` directory is disabled with this module.

See https://nuxtjs.org/api/configuration-generate#routes

**Comment by robyedlin** [comment]
In addition to the router.js file?

**Comment by Atinux** [comment]
Yes, nuxt generate is different than router.js

**Comment by robyedlin** [comment]
Ok cool. Might be worth adding that to the readme. Thanks!
