### ISSUE TITLE
Router module with mode: 'spa'

### ISSUE THREAD

**Issue by robyedlin** [nuxt-community/router-module#5]
I'm getting an error that there is a missing /dist/index.html file when running a build with mode: 'spa' in nuxt.config.js.

Am I missing a config, or is this a bug?

**Comment by robyedlin** [comment]
This worked in nuxt.config.js: 

```
  generate: {
    routes: [
      "/"
    ]
  }
```

Then the server needs to be configured to redirect 404s to /index.html

This would be handy in the docs if you want to change them, or take a PR.

**Comment by Atinux** [comment]
Hi @robyedlin 

A PR to the Readme would be awesome :smile: 

Indeed, since we disable Nuxt.js `pages/` router, Nuxt has no idea the existing routes.

**Comment by robyedlin** [comment]
@Atinux PR submitted!
