### ISSUE TITLE
How to access store from router-module nuxt^2.8.1 ?

### ISSUE THREAD

**Issue by tonimota** [nuxt-community/router-module#51]
I'm using nuxt version **2.8.1** and the new structure Vuex Mode with modules.
[https://nuxtjs.org/guide/vuex-store#activate-the-store](https://nuxtjs.org/guide/vuex-store#activate-the-store)

**About the classic mode vuex:**  _This feature is deprecated and will be removed in Nuxt 3._

About router, i'm using vue-router module to management from route.

I trying to use store in ~/router.js but i'm not getting it....

My structure code 
/store
  - user.js
  - lang.js
/router.js

How to user store in my ~/router.js ?

**Comment by SantaCloze** [comment]
Hey, I just fond the solution > I Post it here in case somebody is searching too.

I used the old version of the store, where you declare a "Vuex Instance" and export it.
The thing is that in Nuxt, the store is a function. And you need to export a function.

So this is my strore :
```
/* eslint-disable camelcase */
import Vuex from 'vuex'

const createStore = () => {
  return new Vuex.Store({
    state: () => ({
      myValue: false,
    }),
    mutations: {
      myExampleMutation(state, myNewValue) {
        state.myValue = myNewValue
      }
    }
  })
}

export default createStore
```
I took 2 hours to understand that as my store is a function, i can call it with a function in my router.

Here is my router :
```
import Vue from 'vue'
import Router from 'vue-router'
import store from "@/store/index";

import Home from './pages/Home.vue'

Vue.use(Router)

const createRouterConst = new Router({
  mode: 'history',
  routes: [
    {
      path: '/',
      name: 'uselessRoute',
      component: Home
    }
  ]
})

  createRouterConst.beforeEach(async (to, from, next) => {
    try {
      console.log(store().myValue); // >>> It's how i call it
      next()
    } catch (error) {
      console.log(error)
    }
  })

export function createRouter() {
  return createRouterConst;
}
```

**Comment by matamune94** [comment]
Have more idea for this, i mean a something better more.
