### ISSUE TITLE
In production mode, only the first visit is valid

### ISSUE THREAD

**Issue by LiuJiangshan** [nuxt-community/router-module#58]

**Comment by LiuJiangshan** [comment]
I think I solved it.
![屏幕快照 2019-09-10 下午3 52 00](https://user-images.githubusercontent.com/13770291/64595270-2b103f00-d3e4-11e9-8f0f-fbd9e1a19282.png)

**Comment by connecteev** [comment]
@LiuJiangshan 2 questions for you

1. what was the issue and what was happening after the 1st visit?

2. Also, why is this router-module needed? I think I read that Nuxt supports extendRoutes by default now -see https://nuxtjs.org/api/configuration-router/#extendroutes (though I haven't used it and don't understand it all that well). Can you clarify?

**Comment by LiuJiangshan** [comment]
@connecteev If you use the right part of the picture above, the second time you can't access it, it will always get stuck. This should be my problem. In addition, I will try extendRoutes, thank you.
