### ISSUE TITLE
named index.vue files

### ISSUE THREAD

**Issue by mrfrase3** [nuxt-community/router-module#66]
### What problem does this feature solve?

It can get a bit confusing/annoying when you have 30 index.vue, or 10 _id.vue files

### What does the proposed changes look like?

the ability to add a name to a dynamic file which is ignored.

e.g. index.users.vue _id.classes.vue index.homepage.vue

<div align="right"><sub><em>This feature request is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/router-module/issues/c49">#c49</a>)</em></sub></div>

**Comment by ricardogobbosouza** [comment]
Hi @mrfrase3 
I did not understand the desired feature, could you explain it better?

**Comment by mrfrase3** [comment]
So in the router for a nuxt application, you use the file names to determine the functionality in the router, (e.g. index.vue and _id.vue) the problem with this is that with a large application, you can easily end up with 30 `index.vue` files, which can be difficult/annoying for a dev to navigate.

What I'm proposing is that anything defined after a dot on a specially named file is ignored, allowing you to have more meaningful file names. so `index.<custom_name>.vue` would be the same as `index.vue`

**Comment by ricardogobbosouza** [comment]
@mrfrase3 with this module you can register your routes as you prefer.

You may be interested in analyzing this other module https://github.com/nuxt-community/router-extras-module
