### ISSUE TITLE
Best way to Write API in Nuxt and Router Module?

### ISSUE THREAD

**Issue by feedgit** [nuxt-community/router-module#9]
I'm finding best way to write API.
Currently, i write api like this:
```
<template>
  <div class="row flex">
    {{data.id}}
  </div>
</template>
<script>
  import axios from 'axios'
  import Item from '~/components/feeds/Post.vue'
  export default {
    data () {
      return {
        data: {}
      }
    },
    mounted () {
      this.asyncData()
    },
    methods: {
      async asyncData (params) {
        let { data } = await axios.get('http://localhost:8000/api/v1/feeds/' + this.$route.params.id + '/')
        this.data = data
      }
    },
    components: {
      'post-detail': Item
    }
  }
</script>
```
But when I get children data: `{{data.user.username}}`,  the data.user goes undefined. Is this the best way to write API data in Nuxt and Router Module?

**Comment by robyedlin** [comment]
`asyncData` is a method on the default object. It's rendered server side, so it won't have access to the component. So you can't use `this`. It should look something like the following:

export default {
    asyncData (context) {
        // your code
    }
}

https://nuxtjs.org/api/

**Comment by feedgit** [comment]
@robyedlin You said right. But when I write API with your way, it goes error: 
![image](https://user-images.githubusercontent.com/19923843/32670706-37b1f946-c677-11e7-947e-9a4a0c6e38ed.png)

So I write API like I did above. Please help me

**Comment by robyedlin** [comment]
@pi0 Please close this issue. I can continue to help @feedgit while this issue is closed.
