### ISSUE TITLE
Error `Template src not found` after upgrading to v1.6.0

### ISSUE THREAD

**Issue by apasov** [nuxt-community/router-module#96]
I rolled back to v1.5.1 and all works fine

![image](https://user-images.githubusercontent.com/28765662/111035625-fa1f2900-8423-11eb-8177-f4a988d3da61.png)

**Comment by ynechaev** [comment]
Had to roll back to `1.5.1` as well.

**Comment by milosb793** [comment]
Getting the same error as well.

**Comment by webzlodimir** [comment]
Same error on 1.5.1
